title: Dewdz's blog
email: wdzdew@126.com
excerpt_separator: '<!-- excerpt -->'
blog_purport: 记录、总结、分享
description: 记录、总结、分享。
permalink: /:categories/:month:day:year/:title
paginate: 2
paginate_path: "page:num"